version: "3"
services:
  target:
    build: ./prometheus-mock
    ports:
     - 30001:30001
  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
  promviz:
    image: nghialv2607/promviz
    ports:
      - 9091:9091
    volumes:
      - ./simple.yaml:/etc/promviz/promviz.yaml
