version: "3"
services:
  target:
    container_name: target
    build: ./prometheus-mock
    ports:
     - 30001:30001
  prometheus:
    container_name: prometheus
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
  vistio:
    container_name: vistio
    image: nmnellis/vistio:latest
    ports:
      - 9091:9091
    volumes:
      - ./full.yaml:/etc/vistio/vistio.yaml
  promviz-front:
    container_name: promviz-front
    image: mjhddevlion/promviz-front:v0.1.0
    ports:
      - 8080:8080
    environment:
      - UPDATE_URL=http://localhost:9091/graph
      - INTERVAL=10000
      - MAX_REPLAY_OFFSET=43200
