version: "3"
services:
  target:
    build: .
    ports:
     - 30001:30001
  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
