[[constraint]]
  name = "github.com/cenkalti/backoff"
  version = "1.1.0"

[[constraint]]
  name = "go.uber.org/zap"
  version = "1.7.1"

[[constraint]]
  name = "gopkg.in/alecthomas/kingpin.v2"
  version = "2.2.5"

[[constraint]]
  name = "gopkg.in/fsnotify.v1"
  version = "1.4.2"
