# # Javascript Node CircleCI 2.0 configuration file
# #
# # Check https://circleci.com/docs/2.0/language-javascript/ for more details
# #
version: 2
jobs:
  build-web:    
    docker:
      - image: circleci/node:10.3.1
        environment:
          DOCKER_IMAGE_NAME: nmnellis/vistio-web

    working_directory: ~/web
    steps:
      - checkout
      - run: npm install
      - setup_remote_docker:
          docker_layer_caching: true
      - run: |
          if [ "${CIRCLE_BRANCH}" == "master" ]; then
            docker build -t $DOCKER_IMAGE_NAME .
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker push $DOCKER_IMAGE_NAME
          fi
          if [[ "$CIRCLE_TAG" =~ ^v[0-9]+(?:\.[0-9]+){2}$ ]]; then
            docker build -t "$DOCKER_IMAGE_NAME:$CIRCLE_TAG" .
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker push "$DOCKER_IMAGE_NAME:$CIRCLE_TAG"
          fi
