apiVersion: v1
kind: Service
metadata:
  name: {{ template "fullname" . }}
  labels:
    heritage: {{ .Release.Service }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    app: {{ template "name" . }}
    release: {{ .Release.Name }}
  {{- if .Values.environment }}
    environment: {{ .Values.environment }}
  {{- end }}
spec:
  type: ClusterIP
  selector:
    app: {{ template "name" . }}
    release: {{ .Release.Name }}
  {{- if .Values.environment }}
    environment: {{ .Values.environment }}
  {{- end }}
  ports:
    - name: web
      port: {{ .Values.service.externalPort }}
      targetPort: {{ .Values.service.internalPort }}
      protocol: TCP
